package com.joshepw.nexusfloatinghelper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

public class MaterialIconHelper {
    public static List<String> getAllIconNames() {
        // Obtener todos los iconos del mapeo y ordenarlos alfabéticamente
        Set<String> iconSet = MaterialSymbolsMapper.getAllIconNames();
        List<String> iconList = new ArrayList<>(iconSet);
        Collections.sort(iconList);
        return iconList;
    }
    
    // Método legacy mantenido por compatibilidad (ya no se usa)
    @Deprecated
    private static List<String> getLegacyIconNames() {
        return java.util.Arrays.asList(
            "home", "settings", "apps", "search", "favorite", "star", "menu", "close",
            "arrow_back", "arrow_forward", "add", "delete", "edit", "check", "cancel",
            "refresh", "more_vert", "more_horiz", "share", "info", "warning", "error",
            "check_circle", "radio_button_checked", "radio_button_unchecked",
            "ac_unit", "mode_fan", "phone", "email", "message", "camera", "photo",
            "video", "music", "play_arrow", "pause", "stop", "volume_up", "volume_down",
            "brightness", "battery", "wifi", "bluetooth", "location_on", "map",
            "directions", "navigation", "restaurant", "hotel", "shopping_cart",
            "payment", "credit_card", "account_balance", "work", "school", "book",
            "library_books", "fitness_center", "sports", "gamepad", "movie", "tv",
            "computer", "laptop", "tablet", "smartphone", "watch", "headphones",
            "speaker", "keyboard", "mouse", "print", "scanner", "folder", "file",
            "cloud", "download", "upload", "sync", "backup", "restore", "lock",
            "lock_open", "security", "vpn_key", "fingerprint", "face", "person",
            "people", "group", "business", "store", "shopping_bag", "local_offer",
            "tag", "label", "bookmark", "flag", "flag_outlined", "notifications",
            "notifications_off", "alarm", "schedule", "event", "calendar_today",
            "access_time", "timer", "hourglass_empty", "history", "update", "autorenew",
            "loop", "repeat", "shuffle", "skip_next", "skip_previous", "fast_forward",
            "fast_rewind", "replay", "forward", "backward", "first_page", "last_page",
            "chevron_left", "chevron_right", "expand_more", "expand_less", "unfold_more",
            "unfold_less", "keyboard_arrow_up", "keyboard_arrow_down", "keyboard_arrow_left",
            "keyboard_arrow_right", "arrow_upward", "arrow_downward", "arrow_left",
            "arrow_right", "trending_up", "trending_down", "trending_flat", "show_chart",
            "bar_chart", "pie_chart", "assessment", "analytics", "insights", "dashboard",
            "widgets", "view_module", "view_list", "view_agenda", "view_stream", "view_week",
            "view_day", "view_carousel", "view_comfy", "view_compact", "grid_view", "list",
            "format_list_bulleted", "format_list_numbered", "sort", "filter_list",
            "tune", "settings_applications", "build", "construction", "engineering",
            "science", "biotech", "medical_services", "local_hospital", "healing",
            "favorite_border", "favorite", "thumb_up", "thumb_down", "star_border",
            "star", "star_half", "grade", "rate_review", "reviews", "comment", "forum",
            "chat", "chat_bubble", "chat_bubble_outline", "question_answer", "help",
            "help_outline", "support", "contact_support", "feedback", "bug_report",
            "report_problem", "report", "assignment", "description", "article", "note",
            "notes", "sticky_note", "text_fields", "title", "format_bold", "format_italic",
            "format_underlined", "format_color_text", "format_size", "format_align_left",
            "format_align_center", "format_align_right", "format_align_justify",
            "format_list_bulleted", "format_list_numbered", "format_quote", "code",
            "functions", "calculate", "functions", "percent", "currency_exchange",
            "attach_money", "monetization_on", "payments", "receipt", "receipt_long",
            "point_of_sale", "storefront", "shopping_cart", "add_shopping_cart",
            "remove_shopping_cart", "shopping_bag", "local_grocery_store", "store",
            "store_mall_directory", "local_mall", "local_offer", "local_activity",
            "local_restaurant", "restaurant_menu", "fastfood", "cake", "coffee", "wine_bar",
            "sports_bar", "nightlife", "local_bar", "hotel", "bed", "accommodation",
            "room_service", "room", "meeting_room", "business_center", "fitness_center",
            "pool", "spa", "beach_access", "golf_course", "casino", "theater_comedy",
            "movie", "live_tv", "tv", "radio", "podcasts", "music_note", "library_music",
            "headphones", "headset", "speaker", "volume_up", "volume_down", "volume_off",
            "volume_mute", "mic", "mic_off", "videocam", "videocam_off", "camera",
            "camera_alt", "camera_enhance", "camera_roll", "photo", "photo_library",
            "photo_camera", "image", "image_search", "collections", "collections_bookmark",
            "wallpaper", "filter", "filter_1", "filter_2", "filter_3", "filter_4",
            "filter_5", "filter_6", "filter_7", "filter_8", "filter_9", "filter_9_plus",
            "filter_b_and_w", "filter_center_focus", "filter_drama", "filter_frames",
            "filter_hdr", "filter_none", "filter_tilt_shift", "filter_vintage",
            "blur_on", "blur_off", "brightness_1", "brightness_2", "brightness_3",
            "brightness_4", "brightness_5", "brightness_6", "brightness_7", "brightness_auto",
            "contrast", "exposure", "exposure_neg_1", "exposure_neg_2", "exposure_plus_1",
            "exposure_plus_2", "exposure_zero", "flare", "grain", "gradient", "hdr",
            "hdr_off", "hdr_on", "hdr_strong", "hdr_weak", "healing", "looks", "looks_3",
            "looks_4", "looks_5", "looks_6", "looks_one", "looks_two", "monochrome_photos",
            "motion_photos_on", "motion_photos_pause", "motion_photos_paused", "nature",
            "nature_people", "navigate_before", "navigate_next", "palette", "photo_album",
            "photo_camera", "photo_filter", "photo_library", "photo_size_select_actual",
            "photo_size_select_large", "photo_size_select_small", "picture_as_pdf",
            "portrait", "rotate_left", "rotate_right", "shutter_speed", "slideshow",
            "straighten", "style", "switch_camera", "switch_video", "tag_faces",
            "texture", "timelapse", "timer", "timer_10", "timer_3", "timer_off", "tonality",
            "transform", "tune", "wb_auto", "wb_cloudy", "wb_incandescent", "wb_iridescent",
            "wb_sunny", "360", "add_a_photo", "add_photo_alternate", "add_to_photos",
            "adjust", "assistant_photo", "audiotrack", "blur_circular", "blur_linear",
            "blur_off", "blur_on", "brightness_1", "brightness_2", "brightness_3",
            "brightness_4", "brightness_5", "brightness_6", "brightness_7", "broken_image",
            "brush", "camera_alt", "camera_front", "camera_rear", "camera_roll", "center_focus_strong",
            "center_focus_weak", "collections", "collections_bookmark", "color_lens",
            "colorize", "compare", "control_point", "control_point_duplicate", "crop",
            "crop_16_9", "crop_3_2", "crop_5_4", "crop_7_5", "crop_din", "crop_free",
            "crop_landscape", "crop_original", "crop_portrait", "crop_rotate", "crop_square",
            "dehaze", "details", "edit", "exposure_neg_1", "exposure_neg_2", "exposure_plus_1",
            "exposure_plus_2", "exposure_zero", "filter", "filter_1", "filter_2", "filter_3",
            "filter_4", "filter_5", "filter_6", "filter_7", "filter_8", "filter_9",
            "filter_9_plus", "filter_b_and_w", "filter_center_focus", "filter_drama",
            "filter_frames", "filter_hdr", "filter_none", "filter_tilt_shift", "filter_vintage",
            "flare", "flash_auto", "flash_off", "flash_on", "flip", "flip_camera_android",
            "flip_camera_ios", "grain", "grid_off", "grid_on", "hdr_off", "hdr_on",
            "hdr_strong", "hdr_weak", "healing", "image", "image_aspect_ratio", "image_not_supported",
            "image_search", "iso", "landscape", "leak_add", "leak_remove", "lens",
            "linked_camera", "looks", "looks_3", "looks_4", "looks_5", "looks_6", "looks_one",
            "looks_two", "loupe", "monochrome_photos", "movie_creation", "movie_filter",
            "music_note", "music_off", "nature", "nature_people", "navigate_before",
            "navigate_next", "palette", "panorama", "panorama_fish_eye", "panorama_horizontal",
            "panorama_vertical", "panorama_wide_angle", "panorama_wide_angle_select",
            "photo", "photo_album", "photo_camera", "photo_filter", "photo_library",
            "photo_size_select_actual", "photo_size_select_large", "photo_size_select_small",
            "picture_as_pdf", "portrait", "remove_red_eye", "rotate_90_degrees_ccw",
            "rotate_left", "rotate_right", "shutter_speed", "slideshow", "straighten",
            "style", "switch_camera", "switch_video", "tag_faces", "texture", "timelapse",
            "timer", "timer_10", "timer_3", "timer_off", "tonality", "transform", "tune",
            "view_comfy", "view_compact", "vignette", "wb_auto", "wb_cloudy", "wb_incandescent",
            "wb_iridescent", "wb_sunny", "add_a_photo", "add_photo_alternate", "add_to_photos",
            "adjust", "assistant_photo", "audiotrack", "blur_circular", "blur_linear",
            "blur_off", "blur_on", "brightness_1", "brightness_2", "brightness_3",
            "brightness_4", "brightness_5", "brightness_6", "brightness_7", "broken_image",
            "brush", "camera_alt", "camera_front", "camera_rear", "camera_roll", "center_focus_strong",
            "center_focus_weak", "collections", "collections_bookmark", "color_lens",
            "colorize", "compare", "control_point", "control_point_duplicate", "crop",
            "crop_16_9", "crop_3_2", "crop_5_4", "crop_7_5", "crop_din", "crop_free",
            "crop_landscape", "crop_original", "crop_portrait", "crop_rotate", "crop_square",
            "dehaze", "details", "edit", "exposure_neg_1", "exposure_neg_2", "exposure_plus_1",
            "exposure_plus_2", "exposure_zero", "filter", "filter_1", "filter_2", "filter_3",
            "filter_4", "filter_5", "filter_6", "filter_7", "filter_8", "filter_9",
            "filter_9_plus", "filter_b_and_w", "filter_center_focus", "filter_drama",
            "filter_frames", "filter_hdr", "filter_none", "filter_tilt_shift", "filter_vintage",
            "flare", "flash_auto", "flash_off", "flash_on", "flip", "flip_camera_android",
            "flip_camera_ios", "grain", "grid_off", "grid_on", "hdr_off", "hdr_on",
            "hdr_strong", "hdr_weak", "healing", "image", "image_aspect_ratio", "image_not_supported",
            "image_search", "iso", "landscape", "leak_add", "leak_remove", "lens",
            "linked_camera", "looks", "looks_3", "looks_4", "looks_5", "looks_6", "looks_one",
            "looks_two", "loupe", "monochrome_photos", "movie_creation", "movie_filter",
            "music_note", "music_off", "nature", "nature_people", "navigate_before",
            "navigate_next", "palette", "panorama", "panorama_fish_eye", "panorama_horizontal",
            "panorama_vertical", "panorama_wide_angle", "panorama_wide_angle_select",
            "photo", "photo_album", "photo_camera", "photo_filter", "photo_library",
            "photo_size_select_actual", "photo_size_select_large", "photo_size_select_small",
            "picture_as_pdf", "portrait", "remove_red_eye", "rotate_90_degrees_ccw",
            "rotate_left", "rotate_right", "shutter_speed", "slideshow", "straighten",
            "style", "switch_camera", "switch_video", "tag_faces", "texture", "timelapse",
            "timer", "timer_10", "timer_3", "timer_off", "tonality", "transform", "tune",
            "view_comfy", "view_compact", "vignette", "wb_auto", "wb_cloudy", "wb_incandescent",
            "wb_iridescent", "wb_sunny"
        );
    }
}

